source 'https://rubygems.org'

ruby '~> 2.7.0'

gem 'jwt',     '~> 2.3'
gem 'octokit', '~> 4.22'

group :development do
  gem 'aws-sdk-secretsmanager', '~> 1.0'
  gem 'datadog-lambda',         '~> 1.14'
  gem 'ddtrace',                '~> 0.53'
  gem 'yake',                   '~> 0.4'
end
