source 'https://rubygems.org'

ruby '2.4.1'

gem 'core', path: '../core'
gem 'persistence', path: '../persistence'
gem 'clients', path: '../clients'

gem 'dotenv'
gem 'rake'

gem 'rails', '~> 5.1.6', '>= 5.1.6.1'
gem 'pg'
gem 'puma', '~> 3.7'

group :development, :test do
  gem 'pry'
  gem 'rb-readline'
end

group :test do
  gem 'rspec'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
