source 'https://rubygems.org'

ruby '2.4.1'

gem 'core', path: '../core'
gem 'persistence', path: '../persistence'
gem 'clients', path: '../clients'

group :test do
  gem 'test_support', path: '../test_support'
end

gemspec

