source 'https://rubygems.org'

ruby '2.4.1'

gem 'core', path: '../core'
gem 'persistence', path: '../persistence'
gem 'clients', path: '../clients'

group :development do
  gem 'pry'
  gem 'rb-readline'
end

group :test do
  gem 'faker'
  gem 'test_support', path: '../test_support'
end

gem 'webpacker'

gemspec

